import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import TransitionEffect from '@/components/TransitionEffect';

 
export default function Home() {
  return (
    <>
      <Head>
        <title>Anil Gaikwad | Home</title>
        <meta name="description" content="Generated by Anil Gaikwad" />
        
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 lg:pt-0 md:pt-16 sm:pt-8'>
          <dev className="flex items-center justify-between w-full lg:flex-col">
              <dev className='w-1/3 md:w-2/3 sm:w-full'>
              <Image src={profilePic} alt="Anil Gaikwad" className='w-full h-auto rounded-l-full border-8 border-transparent lg:hidden md:inline-block md:w-full' 
              priority
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
              </dev>
              <div className='w-2/3 flex flex-col items-center self-center pl-5 lg:w-full lg:text-center'>
                <AnimatedText text="Anil Dipak Gaikwad." className=' !capitalize !text-7xl !text-left font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-violet-600 to-orange-600
                xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-4xl sm:!text-2xl pb-1
                ' />
                <AnimatedText text="Creative Web Designer | Full Stack Java Developer " className='text-primary font-medium !text-xl !text-left lg:!text-center lg:!text-xl md:!text-lg sm:!text-sm' />
                
                <p className='my-4 text-base font-medium md:text-md sm:text-sm'> I am a full stack developer with over 2 years of experience in the field. I specialize in front-end development and have a strong background in ReactJS. I am always looking to learn and grow as a developer, and I am excited to work on new and challenging projects.
                As a skilled Full-Stack Developer, I am dedicated to turning ideas into innovative web applications.
                </p>

                <div className='flex items-center self-start mt-2 lg:self-center'>
                  <Link href="/Resume.pdf" target={"_blank"}
                  className="flex items-center bg-dark text-light p-1 px-4
                  rounded-lg text-lg font-semibold hover:bg-dark hover:text-light
                  border-2 border-solid border-primaryDark hover:border-primary mr-5
                  dark:text-light dark:bg-dark hover:dark:bg-light hover:dark:text-dark dark:border-light md:p-2 md:px-4 md:text-base
                  "
                  >Resume <LinkArrow className={"w-6 ml-1"} />
                  </Link>
                  <Link href="mailto:gaikwadanil530@gmail.com" target={"_blank"}
                  className="flex items-center bg-transparent text-dark p-1 px-4
                  rounded-lg text-lg font-semibold hover:bg-dark hover:text-light
                  border-2 border-solid border-dark hover:border-primary mr-5
                  dark:text-dark dark:bg-light hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base
                  "
                  >Contact
                  </Link>
                </div>

              </div>
          </dev>
        </Layout>

        <HireMe />

        

        <div className='absolute right-32 bottom-12 inline-block w-24 md:hidden'>
          <Image src={lightBulb} alt="Anil" className='w-full h-auto' />
        </div>
      </main>
    </>
  )
}
